import Docker from 'dockerode';
import fs from 'node:fs/promises';
import path from 'node:path';
import { PassThrough } from 'node:stream';

const docker = new Docker({ socketPath: '/var/run/docker.sock' });

export { docker };

export const CONTAINER_IMAGE = 'node:20-alpine';

// 服务器硬约束：沙箱配额
export const CONSTRAINT = {
  Memory: 256 * 1024 * 1024, // 256MB
  CpuQuota: 50000, // 半核（CpuPeriod=100000）
  CpuPeriod: 100000,
  PidsLimit: 100,
  NetworkMode: 'none',
  AutoRemove: true,
};

const EXTERNAL_HARD_TIMEOUT_MS = 120 * 1000;
const TAIL_LINES = 50;

function workspaceRoot() {
  return process.env.WORKSPACE_DIR
    ? path.resolve(process.env.WORKSPACE_DIR)
    : path.resolve(process.cwd(), '../workspace');
}

// 挂载源必须位于 workspace/session-<ts>/build 前缀下，防止把任意宿主目录挂进容器。
export function isBuildDirAllowed(buildDir) {
  const resolved = path.resolve(buildDir);
  const ws = workspaceRoot();
  const rel = path.relative(ws, resolved);
  if (rel.startsWith('..') || path.isAbsolute(rel)) return false;
  const parts = rel.split(path.sep);
  return parts.length === 2 && parts[0].startsWith('session-') && parts[1] === 'build';
}

export function validationScriptText() {
  return `// generated by NL2EARS build sandbox - static validation, then exits.
'use strict';
const fs = require('fs');
const path = require('path');
const http = require('http');
const os = require('os');
const { spawnSync } = require('child_process');

const ROOT = '/app';
const failures = [];
function report(msg) { console.error(msg); failures.push(msg); }

function checkSyntax(content) {
  const tmp = path.join(os.tmpdir(), 'chk-' + Math.random().toString(36).slice(2) + '.js');
  fs.writeFileSync(tmp, content);
  let r = spawnSync('node', ['--check', tmp], { encoding: 'utf8' });
  // 若普通脚本检查失败且内容含 import/export，改用模块方式再试一次
  if (r.status !== 0 && /\\bimport\\s|export\\s+(default|const|let|var|function|class|\\{|\\*)/.test(content)) {
    const tmpM = path.join(os.tmpdir(), 'chk-' + Math.random().toString(36).slice(2) + '.mjs');
    fs.writeFileSync(tmpM, content);
    const r2 = spawnSync('node', ['--input-type=module', '--check', tmpM], { encoding: 'utf8' });
    fs.unlinkSync(tmpM);
    if (r2.status === 0) { fs.unlinkSync(tmp); return null; }
    r = r2;
  }
  fs.unlinkSync(tmp);
  if (r.status !== 0) return r.stderr || 'syntax error';
  return null;
}

function walkJs(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) walkJs(p, out);
    else if (name.endsWith('.js')) out.push(p);
  }
}

// 1. index.html 必须存在
const entry = path.join(ROOT, 'index.html');
if (!fs.existsSync(entry)) {
  report('index.html 不存在');
  console.error('STATIC_SYNTAX_FAIL');
  process.exit(1);
}

const html = fs.readFileSync(entry, 'utf8');

// 1b. HTML 结构完整性校验（防止 LLM 输出被截断成残缺文件却通过验证）
if (!/<body[\\s>]/i.test(html)) report('index.html 缺少 <body> 标签');
if (!/<\\/body>/i.test(html)) report('index.html 缺少 </body> 标签');
if (!/<\\/html>/i.test(html)) report('index.html 缺少 </html> 结束标签');
if (!/<script\\b[^>]*>/i.test(html) && !/<canvas\\b[^>]*>/i.test(html)) {
  report('index.html 未包含任何 <script> 或 <canvas>，疑似内容不完整');
}

// 2a. 校验所有 .js 文件
const jsFiles = [];
walkJs(ROOT, jsFiles);
for (const p of jsFiles) {
  const err = checkSyntax(fs.readFileSync(p, 'utf8'));
  if (err) { report('语法错误 ' + p); report(String(err).slice(0, 1500)); }
}

// 2b. 校验 index.html 内联 <script> 块
const inlineScripts = [];
const re = /<script\\b[^>]*>([\\s\\S]*?)<\\/script>/gi;
let m;
while ((m = re.exec(html))) {
  const body = m[1];
  if (body.trim() && !/<\\/script/i.test(body)) inlineScripts.push(body);
}
inlineScripts.forEach((body, i) => {
  const err = checkSyntax(body);
  if (err) { report('内联 <script> #' + (i + 1) + ' 语法错误'); report(String(err).slice(0, 1200)); }
});

if (failures.length) {
  console.error('STATIC_SYNTAX_FAIL');
  process.exit(1);
}

// 3. 静态服务可达性：node 内置 http 监听 127.0.0.1 随机端口，请求 /index.html 非空即通过
const server = http.createServer((req, res) => {
  const reqPath = decodeURIComponent((req.url || '/').split('?')[0]);
  let fp;
  try { fp = path.join(ROOT, reqPath === '/' ? '/index.html' : reqPath); } catch { res.writeHead(400); res.end(); return; }
  const rel = path.relative(ROOT, fp);
  if (rel.startsWith('..') || path.isAbsolute(rel)) { res.writeHead(404); res.end(); return; }
  fs.stat(fp, (e, st) => {
    if (e || !st.isFile()) { res.writeHead(404); res.end(); return; }
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(fs.readFileSync(fp));
  });
});

server.listen(0, '127.0.0.1', () => {
  const port = server.address().port;
  const req = http.get({ host: '127.0.0.1', port, path: '/index.html', timeout: 5000 }, (res) => {
    let data = '';
    res.on('data', (c) => { data += c; });
    res.on('end', () => {
      server.close();
      if (data.length >= 500) {
        console.log('VALIDATION_PASS');
        process.exit(0);
      }
      report('index.html 返回内容过少（疑似残缺文件）');
      console.error('STATIC_SYNTAX_FAIL');
      process.exit(1);
    });
  });
  req.on('error', () => { server.close(); report('服务可达性检查失败'); console.error('STATIC_SYNTAX_FAIL'); process.exit(1); });
  req.on('timeout', () => { server.close(); report('服务可达性检查超时'); console.error('STATIC_SYNTAX_FAIL'); process.exit(1); });
});
`;
}

// node-service 运行时验证：语法检查 + 启动 server.js + GET / 必须 200。
export function serviceValidationScriptText() {
  return `// generated by NL2EARS build sandbox - node-service validation, then exits.
'use strict';
const fs = require('fs');
const path = require('path');
const http = require('http');
const os = require('os');
const { spawn, spawnSync } = require('child_process');

const ROOT = '/app';
const failures = [];
function report(msg) { console.error(msg); failures.push(msg); }

function checkSyntax(content) {
  const tmp = path.join(os.tmpdir(), 'chk-' + Math.random().toString(36).slice(2) + '.js');
  fs.writeFileSync(tmp, content);
  const r = spawnSync('node', ['--check', tmp], { encoding: 'utf8' });
  fs.unlinkSync(tmp);
  if (r.status !== 0) return r.stderr || 'syntax error';
  return null;
}

function walkJs(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) walkJs(p, out);
    else if (name.endsWith('.js')) out.push(p);
  }
}

// 1. server.js 必须存在
const entry = path.join(ROOT, 'server.js');
if (!fs.existsSync(entry)) {
  report('server.js 不存在');
  console.error('STATIC_SYNTAX_FAIL');
  process.exit(1);
}

// 2. 校验所有 .js 文件语法
const jsFiles = [];
walkJs(ROOT, jsFiles);
for (const p of jsFiles) {
  const err = checkSyntax(fs.readFileSync(p, 'utf8'));
  if (err) { report('语法错误 ' + p); report(String(err).slice(0, 1500)); }
}
if (failures.length) {
  console.error('STATIC_SYNTAX_FAIL');
  process.exit(1);
}

// 3. 启动 server.js，GET / 必须 200（沙箱断网，验证启动不依赖外网）
const PORT = 4399;
const child = spawn('node', [entry], {
  env: { ...process.env, PORT: String(PORT) },
  stdio: ['ignore', 'pipe', 'pipe'],
});
let errTail = '';
child.stderr.on('data', (c) => { errTail = (errTail + c).slice(-2000); });
child.on('error', (e) => { report('server.js 启动失败: ' + e.message); console.error('STATIC_SYNTAX_FAIL'); process.exit(1); });

const deadline = Date.now() + 15000;
function fail(msg) {
  child.kill('SIGKILL');
  report(msg);
  if (errTail.trim()) console.error(errTail);
  console.error('STATIC_SYNTAX_FAIL');
  process.exit(1);
}
function tryGet() {
  if (Date.now() > deadline) return fail('服务未在 15s 内就绪（GET / 无 200 响应）');
  const req = http.get({ host: '127.0.0.1', port: PORT, path: '/', timeout: 3000 }, (res) => {
    let data = '';
    res.on('data', (c) => { data += c; });
    res.on('end', () => {
      if (res.statusCode === 200 && data.length >= 100) {
        child.kill('SIGKILL');
        console.log('VALIDATION_PASS');
        process.exit(0);
      }
      fail('GET / 返回 ' + res.statusCode + '（内容 ' + data.length + 'B，要求 200 且 ≥100B）');
    });
  });
  req.on('error', () => setTimeout(tryGet, 300));
  req.on('timeout', () => { req.destroy(); setTimeout(tryGet, 300); });
}
setTimeout(tryGet, 300);
`;
}

// 管理员手动预拉镜像（导出供部署脚本使用；禁止在请求路径上在线拉镜像）。
export async function pullTemplateImage() {
  const exists = await docker.getImage(CONTAINER_IMAGE).inspect().then(() => true).catch(() => false);
  if (exists) return true;
  console.log('[sandbox] 基础镜像不存在，请先执行 setup-build-env.sh 预拉镜像');
  return false;
}

function tailLines(text, n = TAIL_LINES) {
  if (!text) return '';
  const lines = text.split('\n');
  return lines.slice(-n).join('\n');
}

async function runContainerOnce(buildDir) {
  const container = await docker.createContainer({
    Image: CONTAINER_IMAGE,
    Cmd: ['node', '/app/_validate.cjs'],
    HostConfig: {
      Binds: [`${buildDir}:/app:ro`],
      AutoRemove: CONSTRAINT.AutoRemove,
      Memory: CONSTRAINT.Memory,
      CpuQuota: CONSTRAINT.CpuQuota,
      CpuPeriod: CONSTRAINT.CpuPeriod,
      PidsLimit: CONSTRAINT.PidsLimit,
      NetworkMode: CONSTRAINT.NetworkMode,
      ReadonlyRootfs: true,
      Tmpfs: { '/tmp': 'rw,size=16m,mode=1777' },
    },
    Tty: false,
  });

  let stdout = '';
  let stderr = '';
  let exitCode = null;
  const startTime = Date.now();
  let timedOut = false;
  const timer = setTimeout(() => { timedOut = true; }, EXTERNAL_HARD_TIMEOUT_MS);

  try {
    // docker 非 TTY 模式下 attach 输出是多路复用协议（每条数据带 8 字节帧头，含 NUL 字节），
    // 必须经 demuxStream 分离 stdout/stderr，否则 NUL 会污染 stderr 文本并在后续 git commit -m 时报错。
    const stdoutS = new PassThrough();
    const stderrS = new PassThrough();
    stdoutS.on('data', (c) => { stdout += c.toString('utf8'); });
    stderrS.on('data', (c) => { stderr += c.toString('utf8'); });
    const stream = await container.attach({ stream: true, stdout: true, stderr: true });
    container.modem.demuxStream(stream, stdoutS, stderrS);
    await container.start();
    const res = await container.wait();
    exitCode = res && typeof res.StatusCode === 'number' ? res.StatusCode : null;
  } catch (e) {
    stderr += `\n[container] ${e.message}`;
  } finally {
    clearTimeout(timer);
  }

  if (timedOut) {
    await container.kill().catch(() => {});
    return { exitCode: 124, timedOut: true, stdout, stderr };
  }
  return { exitCode, timedOut: false, stdout, stderr };
}

// —— 串行队列：同时最多 1 个沙箱在跑，其余排队 ——
const queue = [];
let running = false;

function drain() {
  if (running) return;
  const next = queue.shift();
  if (!next) return;
  running = true;
  next.task()
    .then((r) => { next.resolve(r); running = false; drain(); })
    .catch((e) => { next.reject(e); running = false; drain(); });
}

export function enqueueSandbox(task) {
  return new Promise((resolve, reject) => {
    queue.push({ task, resolve, reject });
    drain();
  });
}

export function queueStats() {
  return { running, queued: queue.length };
}

export async function runValidation(buildDir, runtime = 'static-web') {
  if (!isBuildDirAllowed(buildDir)) {
    return { passed: false, exitCode: 1, stdoutTail: '', stderrTail: '拒绝: buildDir 不在 workspace/session-*/build 前缀下', errorType: 'path' };
  }
  const scriptPath = path.join(buildDir, '_validate.cjs');
  try {
    const text = runtime === 'node-service' ? serviceValidationScriptText() : validationScriptText();
    await fs.writeFile(scriptPath, text, 'utf8');
  } catch (err) {
    return { passed: false, exitCode: 1, stdoutTail: '', stderrTail: '写验证脚本失败: ' + err.message, errorType: 'write' };
  }

  let raw;
  try {
    raw = await enqueueSandbox(() => runContainerOnce(buildDir));
  } catch (err) {
    raw = { exitCode: null, timedOut: false, stdout: '', stderr: '调度沙箱失败: ' + err.message };
  } finally {
    await fs.rm(scriptPath, { force: true }).catch(() => {});
  }

  const passed = !raw.timedOut && raw.exitCode === 0;
  const errorType = raw.timedOut ? 'timeout' : raw.exitCode === 0 ? null : 'runtime';
  return {
    passed,
    exitCode: raw.exitCode,
    stdoutTail: tailLines(raw.stdout),
    stderrTail: tailLines(raw.stderr),
    errorType,
  };
}